/** @type {import('tailwindcss').Config} */

export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
    "./assets/primevueThemes/**/*.{js,vue,ts}",
  ],
  darkMode: ["selector", '[class*="dark-mode"]'],
  theme: {
    extend: {
      borderRadius: {
        button: "4px",
      },
      colors: {
        disabledInputBg: "rgb(243 244 246)",
        inputPlaceholder: "rgb(156 163 175)",
        disabledInputPlaceholder: "rgb(156 163 175)",
        disabledInputText: "rgb(75 85 99)",
        disabledBorder: "rgb(209 213 219)",
        primary: {
          0: "var(--cl-primary-0)",
          50: "var(--cl-primary-50)",
          100: "var(--cl-primary-100)",
          200: "var(--cl-primary-200)",
          300: "var(--cl-primary-300)",
          400: "var(--cl-primary-400)",
          500: "var(--cl-primary-500)",
          600: "var(--cl-primary-600)",
          700: "var(--cl-primary-700)",
          800: "var(--cl-primary-800)",
          900: "var(--cl-primary-900)",
          950: "var(--cl-primary-950)",
        },
        secondary: {
          50: "var(--cl-secondary-50)",
          100: "var(--cl-secondary-100)",
          200: "var(--cl-secondary-200)",
          300: "var(--cl-secondary-300)",
          400: "var(--cl-secondary-400)",
          500: "var(--cl-secondary-500)",
          600: "var(--cl-secondary-600)",
          700: "var(--cl-secondary-700)",
          800: "var(--cl-secondary-800)",
          900: "var(--cl-secondary-900)",
          950: "var(--cl-secondary-950)",
        },
        error: "var(--cl-error)",
        fav: "var(--cl-fav)",
        grayscale: {
          50: "var(--cl-secondary-50)",
          100: "var(--cl-secondary-100)",
          200: "var(--cl-secondary-200)",
          300: "var(--cl-secondary-300)",
          400: "var(--cl-secondary-400)",
          500: "var(--cl-secondary-500)",
          600: "var(--cl-secondary-600)",
          700: "var(--cl-secondary-700)",
          800: "var(--cl-secondary-800)",
          900: "var(--cl-secondary-900)",
          950: "var(--cl-secondary-950)",
        },
        bluegray: {
          50: "var(--cl-bluegray-50)",
          100: "var(--cl-bluegray-100)",
          200: "var(--cl-bluegray-200)",
          300: "var(--cl-bluegray-300)",
          400: "var(--cl-bluegray-400)",
          500: "var(--cl-bluegray-500)",
          600: "var(--cl-bluegray-600)",
          700: "var(--cl-bluegray-700)",
          800: "var(--cl-bluegray-800)",
          900: "var(--cl-bluegray-900)",
        },
        success: {
          50: "var(--cl-success-50)",
          100: "var(--cl-success-100)",
          200: "var(--cl-success-200)",
          300: "var(--cl-success-300)",
          400: "var(--cl-success-400)",
          500: "var(--cl-success-500)",
          600: "var(--cl-success-600)",
          700: "var(--cl-success-700)",
          800: "var(--cl-success-800)",
          900: "var(--cl-success-900)",
          950: "var(--cl-success-950)",
        },
        warning: {
          50: "var(--cl-warning-50)",
          100: "var(--cl-warning-100)",
          200: "var(--cl-warning-200)",
          300: "var(--cl-warning-300)",
          400: "var(--cl-warning-400)",
          500: "var(--cl-warning-500)",
          600: "var(--cl-warning-600)",
          700: "var(--cl-warning-700)",
          800: "var(--cl-warning-800)",
          900: "var(--cl-warning-900)",
          950: "var(--cl-warning-950)",
        },
        "app-background": "#E6EBF1",
        inputDisabled: "rgba(239, 239, 239, 0.3)",
      },
      fontFamily: {
        primary: ["Inter", "sans-serif"],
        secondary: ["Inter", "sans-serif"],
      },
      fontSize: {
        xxs: [
          "0.625rem",
          {
            lineHeight: "0.875rem",
          },
        ],
      },
      gap: {
        button: "8px",
        "button-container": "8px",
        "inner-elements": "8px",
        input: "8px",
        "input-container": "24px",
        section: "32px",
      },
      gridTemplateColumns: {
        responsive: "repeat(auto-fill, minmax(244px, 1fr))",
      },
      height: {
        "header-height": "55px",
        button: "36px",
        input: "36px",
        "datatable-row": "52px",
      },
      maxHeight: ({ theme }) => ({
        ...theme("height"),
      }),
      minHeight: ({ theme }) => ({
        ...theme("height"),
      }),
      maxWidth: ({ theme }) => ({
        ...theme("width"),
      }),
      minWidth: ({ theme }) => ({
        ...theme("width"),
      }),
      screens: {
        ms: "320px",
        mm: "375px",
        ml: "425px",
        tab: "768px",
        lt: "1024px",
        ltl: "1440px",
        dt: "1920px",
        "4k": "2560px",
      },
      size: {
        22: "88px",
      },
      spacing: {
        "header-height": "55px",
        "sidebar-width": "80px",
        "submenu-width": "240px",
        unset: "unset",
        button: "8px 12px",
        input: "8px 12px",
        section: "32px 24px",
        "section-x": "1.5rem",
        "section-y": "2rem",
      },
      transitionDuration: {
        short: "100ms",
        normal: "200ms",
        long: "300ms",
      },
      transitionProperty: {
        width: "width",
      },
      width: {
        "sidebar-width": "80px",
        "submenu-width": "240px",
        "fullsidebar-width": "320px",
      },
    },
  },
  plugins: [require("tailwindcss-primeui")],
};
